- name: create app
  dokku_app:
    app: repos
- name: redis:create default
  dokku_service_create:
    name: default
    service: redis
- name: postgres:create default
  dokku_service_create:
    name: default
    service: postgres
- name: redis:link default repos
  dokku_service_link:
    app: repos
    name: default
    service: redis
- name: postgres:link default repos
  dokku_service_link:
    app: repos
    name: default
    service: postgres
- name: environment configuration
  dokku_config:
    app: repos
    config:
      RAILS_ENV: "production"
      RAILS_MASTER_KEY: "{{ lookup('ansible.builtin.env', 'RAILS_MASTER_KEY') }}"
      RAILS_SERVE_STATIC_FILES: "true"
      API_HOST: "https://data.code.gouv.fr"
      SIDEKIQ_USERNAME: "{{ lookup('ansible.builtin.env', 'SIDEKIQ_USERNAME') }}"
      SIDEKIQ_PASSWORD: "{{ lookup('ansible.builtin.env', 'SIDEKIQ_PASSWORD') }}"
      SKIP_USER_REPOS: "1"
- name: git clone
  dokku_clone:
    app: repos
    repository: https://github.com/codegouvfr/ecosystems-repos.git
    version: improve-dinum-synchro
- name: domain
  dokku_domains:
    app: repos
    domains:
      - repos.data.code.gouv.fr
      - data.code.gouv.fr
- name: domains:remove repo.dokku.me
  dokku_domains:
    app: repos
    domains:
      - repos.dokku.me
    state: absent
- name: Set letsencrypt email (repos)
  ansible.builtin.shell: dokku letsencrypt:set repos email tech@code.gouv.fr
- name: Enable letsencrypt (repos)
  dokku_letsencrypt:
    app: repos
- name: scale web and worker processes
  dokku_ps_scale:
    app: repos
    scale:
      web: 1
      worker: 1